project_id = "xdltjsdhtcohyhwzcpsx"

[functions.sync-bm-accounts]
verify_jwt = false

[functions."update-spend-cap"]
verify_jwt = false

[functions.scheduled-sync]
verify_jwt = false

[functions.rename-ad-account]
verify_jwt = false

[functions.get-account-insights]
verify_jwt = false
